import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideMenu from "./components/navigation/SideMenu";
import "@fortawesome/fontawesome-svg-core/styles.css"
import {config} from "@fortawesome/fontawesome-svg-core";
import { ApolloProvider } from "@apollo/client";
import { client } from "./lib/apollo-client";
import ApolloWrapper from "./lib/ApolloWrapper";

config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-cols-[0.1fr_0.9fr] w-screen h-screen m-0 p-0 bg-[#F8F9FA] overflow-x-hidden`}
      >
        <SideMenu/>
        <main className="overflow-x-hidden overflow-y-auto w-full h-full p-0 m-0">
          <ApolloWrapper>{children}</ApolloWrapper>
        </main>          
      </body>
    </html>
  );
}
